### ISSUE TITLE
Hardware Revision check incomplete

### ISSUE THREAD

**Issue by chrostek** [j-a-n/raspberrymatic-addon-rmupdate#1]
Hi,

the hardware revision check is incomplete. i have an rpi3 with a02082 and an rpi2 with a01041.
you are checking only one revision per rpi-version, but there are much more:

http://elinux.org/RPi_HardwareHistory

can you please complete your check with the revisions from this list?

thanks!

**Comment by j-a-n** [comment]
Thanks for reporting.
