### ISSUE TITLE
Can't access the gui anymore after upgrading to 1.13.1

### ISSUE THREAD

**Issue by TheUntouchable** [j-a-n/raspberrymatic-addon-rmupdate#12]
After the upgrade to the latest version, I got an username/password form that I never got till now. I closed the rmupdate page and tried to access the page over the homematic webui under system control --> system update but I got a 404. I did this update over the rmupdate itself and I don't use a passwort to authentificate on the raspberrymatic. 

Do you need any futher information for that problem? :)

PS: A reboot  of my RPI2 with firmware 2.35.16.20180715 didn't fix that problem.

**Comment by j-a-n** [comment]
Yes, the addon is now password protected.
You can use the same credentials as for the CCU login.
Indeed, the link to the addon under system control was broken.
This is fixed in 1.13.2.
