### ISSUE TITLE
Probleme mit RaspberryMatic Version 2.35.16.20180715 und aktuellster rmupdate Version

### ISSUE THREAD

**Issue by GENxD** [j-a-n/raspberrymatic-addon-rmupdate#13]
Hallo!

Die neuste Version des rmupdate Addons funktioniert nicht mit der RaspberryMatic Version 2.35.16.20180715. Ich habe die RaspberryMatic Version RaspberryMatic-2.31.25.20180120-rpi3.rmupdate.img und das Addon rmupdate vom 18.02.2018 installiert. Hier hat alles funktioniert und ich konnte auch die Firmware-Updates über den Button "System Update" durchführen.

Mit der neusten Version jedoch lädt es die Firmware-Updates und auch die Addon Informationen nicht mehr auf der Seite. Habe leider nicht mehr die komplette Fehlermeldung ("..no such element in array..").

Außerdem lädt die komplette CCU Seite nach ca. 1 Sekunde neu, sobald ich auf den Button "Zusatzsoftware" geklickt habe. Ich habe hier nicht einmal die Möglichkeit irgendetwas zu klicken.

Als Addons sind nur CUx-Daemon in Version 2.0.1 installiert.

Bitte um Rückmeldung, falls weitere Informationen benötigt werden.

Vielen Dank für die Unterstützung!

Gruß!

**Comment by j-a-n** [comment]
Hallo,

ist für den User Admin ein Passwort gesetzt?

Grüße
Jan

**Comment by GENxD** [comment]
Hallo,

danke für die schnelle Reaktion! 👍 

Ja der Admin hat ein Passwort. Das ist das Passwort, welches ich beim SSH Zugang gesetzt habe und mit dem ich mich als root dann auch via SSH einloggen kann.

D.h. den Pi ohne Passwort verwenden und dann sollte es gehen?

Grüße!

**Comment by j-a-n** [comment]
Im Gegenteil, versuche mal bitte für den Admin ein Passwort für die Webui zu setzen.

**Comment by GENxD** [comment]
Der Admin-User für die Webui hat ein Passwort gesetzt. Habe es über die Datei /etc/config/homematic.regadom geprüft. Dort ist unter dem <name>Admin</name> im Feld <pwmd5> ein Hashwert eingetragen. Und wenn ich in der Webui auf Abmelden klicken, muss ich mich auch mit Admin und dem Passwort anmelden.

**Comment by j-a-n** [comment]
Kannst Du bitte einmal die Browser-Konsole öffnen und dann den Fehler nochmal reproduzieren?
https://kb.mailster.co/how-can-i-open-the-browsers-console/
Bitte den Output der Konsole dann bereitstellen.

**Comment by GENxD** [comment]
Aktueller Stand:
2.35.16.20180715
RMUpdate Version 1.8.4

Fehlermeldung beim Klicken auf Button "System-Update":
Ein Fehler ist aufgetreten: can&#39;t read &quot;addons(rmupdate::available_version)&quot;: no such element in array

Fehlermeldung beim Klicken auf Button "Zusatzsoftware":
![addons](https://user-images.githubusercontent.com/42152465/43890529-50f1cd5c-9bc7-11e8-840f-bb50fe53801a.jpg)

Addons:
![browser-console](https://user-images.githubusercontent.com/42152465/43890518-4a412674-9bc7-11e8-8a20-e68f40c684fd.jpg)

**Comment by GENxD** [comment]
Ich habe jetzt noch die aktuellste rmupdate Version 1.13.2 installiert und bekomme hier auch weiterhin Fehler:

Fehlermeldung beim Drücken auf Button "Zusatzsoftware":
![addons2](https://user-images.githubusercontent.com/42152465/43891290-3a88e4cc-9bc9-11e8-8d92-30df858a3f65.jpg)

Fehlermeldung beim Drücken auf Button "System-Update":
![system-update](https://user-images.githubusercontent.com/42152465/43891299-3da57d00-9bc9-11e8-9625-7962f542fbc4.jpg)

**Comment by j-a-n** [comment]
Sieht mir nach einem Problem mit der Verbindung zu Github aus.
Bitte einmal folgenden Befehl per SSH auf der RaspberryMatic ausführen:
`/usr/bin/wget -q --no-check-certificate -O- "https://github.com/j-a-n/raspberrymatic-addon-rmupdate/raw/master/VERSION"`
Die Ausgabe bitte hier posten.

**Comment by GENxD** [comment]
Habe den Befehl ausgeführt, x2, aber jedes Mal passiert einfach nichts:
![2018-08-11 20_27_08-192 168 178 90 - putty](https://user-images.githubusercontent.com/42152465/43994902-00c70a56-9da5-11e8-94bb-be4f7e4faaa5.jpg)

**Comment by j-a-n** [comment]
Bitte mal den Befehl ohne "-q" ausführen.

**Comment by GENxD** [comment]
Danke für den Hinweis! Ich habe den Befehl ohne "-q" ausgeführt. Habe den Fehler auch schon gefunden: ich hatte einen Zahlendreher in der IP-Adresse vom Standard-Gateway und habe diesen leider nicht gleich gesehen -.-

Jetzt funktioniert die System-Update Seite und auch die CCU Seite lädt nicht mehr neu, wenn ich auf den Button "Zusatzsoftware" klicke.

**Vielen Dank für deine Unterstützung!** 👍
