### ISSUE TITLE
Bei aktivierter HTTP Auth keine Update von Zusatzsoftware möglich.

### ISSUE THREAD

**Issue by libertyx82** [j-a-n/raspberrymatic-addon-rmupdate#14]
Hi,

wenn man auf der CCU / RaspMatic  HTTP auth aktiviert, funktioniert die Prüfung auf die neuste Version von Addons nicht mehr und somit ist auch eine Aktualisierung nicht mehr möglich.

**Comment by j-a-n** [comment]
Wie ist http auth konfiguriert?

**Comment by libertyx82** [comment]
So das jeder Aufruf von /config & /addons authentifiziert werden muss

```
auth.backend = "htpasswd" 
auth.backend.htpasswd.userfile = "/etc/config/lighttpd/.lighttpdpassword"
auth.require = (
        "/config/" =>
        (
                "method" => "basic",
                "realm" => "api",
                "require" => "valid-user"
        ),
        "/addons/" =>
        (
                "method" => "basic",
                "realm" => "api",
                "require" => "valid-user"
        )

)
```

**Comment by j-a-n** [comment]
Bitte mal versuchen, ob es mit der rmupdate Version 1.13.3 funktioniert.

**Comment by libertyx82** [comment]
hm-watchdog, Script-Parser & XML-API zeigen eine Version an, neu installieren geht aber nicht.

![image](https://user-images.githubusercontent.com/22996350/44679668-e5344300-aa3b-11e8-80ac-4e70008a1d16.png)

**Comment by j-a-n** [comment]
Bitte nochmal die 1.13.4 versuchen. Danke!

**Comment by libertyx82** [comment]
Läuft! :) Vielen Dank!

![image](https://user-images.githubusercontent.com/22996350/44682635-347e7180-aa44-11e8-83a5-19355251e3dd.png)

**Comment by j-a-n** [comment]
Sehr gut, Danke für die Rückmeldung!
