### ISSUE TITLE
Neustart bzw herunterfahren

### ISSUE THREAD

**Issue by MathiasJZ** [j-a-n/raspberrymatic-addon-rmupdate#15]
Hi zusammen,
folgendes Problem:
Ich muß mich zwar einloggen, um rmupdate nutzen zu können.
klicke ich den Login einfach weg, ist es trotzdem möglich, das System neu zu starten oder herunter zu fahren.
Gruß,
Mathias

**Comment by j-a-n** [comment]
Die Buttons werden zwar angezeigt, sollten jedoch nicht funktionieren.

**Comment by MathiasJZ** [comment]
Ich werde es morgen nochmal testen.
Gruß,
Mathias

Am 27. August 2018 22:11:10 schrieb j-a-n <notifications@github.com>:
