### ISSUE TITLE
Anzeige der Verfügbaren Version nicht mehr korrekt nach Anpassungen des Update Check FW3.41.x

### ISSUE THREAD

**Issue by libertyx82** [j-a-n/raspberrymatic-addon-rmupdate#17]
Nach der Anpassung des Update Check von verschiedenen Addon's

z.B. HM_Mail https://github.com/jens-maus/hm_email/commit/b2327178341aff5bbc264931e3c41ca3de1a8aea

Wird die Verfügbare Version nicht mehr korrekt angezeigt. (Codierung)
![screencapture_122367656_2391652524_0](https://user-images.githubusercontent.com/22996350/49045617-d6dbfb80-f1d1-11e8-94b3-cddd039e95ae.jpg)

**Comment by j-a-n** [comment]
Behoben in 1.13.5.
