### ISSUE TITLE
RedMatic Versionsabfrage funktioniert nicht mehr

### ISSUE THREAD

**Issue by hobbyquaker** [j-a-n/raspberrymatic-addon-rmupdate#18]
Ging mit 1.13.2 noch, mit 1.13.9 nicht mehr, siehe https://github.com/HM-RedMatic/RedMatic/issues/116

Kannst Du da mal draufschauen? Kann es am Content-Type Header liegen? Ich setz da `text/html`

**Comment by j-a-n** [comment]
Das Problem wurde durch das /usr/bin/env im Shebang des update_check.cgi verursacht.
Fixed in 1.13.10
