### ISSUE TITLE
After upgrade to latest RaspberryMatic through rmupdate no boot possible

### ISSUE THREAD

**Issue by TheUntouchable** [j-a-n/raspberrymatic-addon-rmupdate#20]
Hi guys!
Never had problems with this wonderful piece of software till now so thanks a lot :D

Sadly after I started the upgrade to the latest version of RasperryMatic yesterday the RasperryPI does strange things when I reboot it (did the hardreboot after I didn't get any response for more than one day):

First its telling me that its booting into recovery mode.
Afterwards I see the RasperryMatic boot screen and it stops with the message "Starting MountAll".
Red LED of the RPi 2 is blinking, sometimes the green one too.

Nothing will ever happen, no matter how long you wait.

Any change I get it running again without loosing all my configurations? :D

Thank you in advanced!

Michael

PS: Tried 3 different power supplies with over 2A output each

**Comment by TheUntouchable** [comment]
Okay, after I had a look at the boot partition I saw that the bootloader is checking for files in the userfs. Mounted that patition, deleted .firmwareUpdate and .recoveryMode, and now the old system is booting again. ;)

**Comment by TheUntouchable** [comment]
Retried the update, same problem even though the log says everything was alright:

```
Firmware 3.41.11.20190126 erfolgreich installiert.

Lade Firmware von https://github.com/jens-maus/RaspberryMatic/releases/download/3.41.11.20190126/RaspberryMatic-3.41.11.20190126-rpi3.zip herunter.

     0K ........ ........ ........ ........ 15% 4.19M 42s
 32768K ........ ........ ........ ........ 30% 1.41M 68s
 65536K ........ ........ ........ ........ 46% 4.15M 44s
 98304K ........ ........ ........ ........ 61% 1.77M 35s
131072K ........ ........ ........ ........ 77% 3.70M 19s
163840K ........ ........ ........ ........ 92% 3.09M 6s
196608K ........ ......                    100% 3.08M=80s

Download abgeschlossen.
Entpacke Firmware RaspberryMatic-3.41.11.20190126-rpi3.zip.
Bitte haben Sie ein wenig Geduld, dieser Vorgang benötigt einige Minuten...
Verwende Recovery-System für Firmware-Update.
Das Recovery-System wird nun gestartet und das Firmware-Update durchgeführt.
Bitte haben Sie ein wenig Geduld, dieser Vorgang benötigt einige Minuten...
```

**Comment by TheUntouchable** [comment]
Unfortunately, the last update attempt seems to have killed the installation completely, no boot possible even after deleting the files, it always restarts into recovery

**Comment by j-a-n** [comment]
The recovery system of RaspberryMatic failes to mount filesystems if the mbr signature is not "deedbeef".
Version 1.13.12 will correct mbr signature before reboot if needed.

**Comment by TheUntouchable** [comment]
Any way I can do this fix manual on the filesystem so I don't have to setup the installation again? Sadly I am not able to boot into the old installation anymore.

**Comment by j-a-n** [comment]
Deleting .firmwareUpdate and .recoveryMode should be sufficient. Any messages on the screen?

**Comment by TheUntouchable** [comment]
Sadly this only worked for the first try.. After a second try to flash the new firmeware with rmupdate it only boots into the recovery, even when I edit the boot config to not boot into recovery it trys to boot to network and not to rootfs..

**Comment by j-a-n** [comment]
Put the SD-Card into a Computer copy contents from partition 3 (userfs) to the computer. Reflash SD-Card with a clean RaspberryMatic. Put the card back into the Raspi. Boot once to auto resize the userfs. Put card back into the computer a copy contents of userfs back to partition 3.

**Comment by TheUntouchable** [comment]
Thanks a lot for that hint! All seems to work again but sadly no of my installed plugins. They are shown in the system control but if I click on them my browser wants do download webpages.. Also the addon managment of raspberrymatic shows no addons installed. Tried to reinstall, reinstall - uninstall - reinstall, but both ways didn't work. Do you have any hint to reset the plugins? Sadly I am not able to restore a backup because of incorrect password..

**Comment by j-a-n** [comment]
Most likely this is a problem with symlinks.
How did you copy the data?
Best way would be to use tar to keep symlinks and permissions intact.

**Comment by TheUntouchable** [comment]
Yeah.. Never thought about that..
The problem is that I copied that files on my windows machine with Paragon Linux File Systems for Windows as i didn't had any linux distro here at this time. So no wonder that symlinks are missing.. :( So the backup of the userfs is worth nothing
