### ISSUE TITLE
Keine Laufwerke / Software in Raspberrymatic

### ISSUE THREAD

**Issue by ThomasRi333** [j-a-n/raspberrymatic-addon-rmupdate#21]
Hallo Jan, ersteinmal danke für deine Arbeit.
Leider habe ich folgenden Bug:
Es werden keine Laufwerke angezeigt, es kommt die Fehlermeldung "Bad Gateway".
Trat im Produktivsystem auf, ein neu aufgesetztes Testsystem zeigt den gleichen Fehler.
![RmUpdate](https://user-images.githubusercontent.com/59541201/71844369-42c3af80-30c6-11ea-9408-8d5e630bd42d.JPG)
![Rmupdate2](https://user-images.githubusercontent.com/59541201/71844383-48b99080-30c6-11ea-95ea-8694d4cbfb6f.JPG)

**Comment by j-a-n** [comment]
Hallo Thomas,

installiere bitte die neueste Version 1.13.14.
Die behebt den Fehler zwar nicht, es sollte dann aber eine aussagekräftige Fehlermeldung angezeigt werden.

Grüße
Jan

**Comment by ThomasRi333** [comment]
Hallo Jan, was für Infos kann ich dir noch zukommen lassen ?

Im Pop-Up Fenster: Ein Fehler ist aufgetreten: child process exited abnormally

![Rmupdate4](https://user-images.githubusercontent.com/59541201/71853953-1b2c1180-30dd-11ea-85f6-c6e8db311ea6.JPG)

**Comment by j-a-n** [comment]
Bitte per SSH auf der CCU folgende Befehle ausführen und die Ausgaben hier posten.
```/sbin/fdisk -l```
```/bin/df -a -T```

**Comment by ThomasRi333** [comment]
Hallo Jan,
hier die Ausgabe:

/media/usb1/backup$ /sbin/fdisk -l

Disk /dev/ram0: 4 MiB, 4194304 bytes, 8192 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes


Disk /dev/ram1: 4 MiB, 4194304 bytes, 8192 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes


Disk /dev/ram2: 4 MiB, 4194304 bytes, 8192 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes


Disk /dev/ram3: 4 MiB, 4194304 bytes, 8192 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes


Disk /dev/ram4: 4 MiB, 4194304 bytes, 8192 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes


Disk /dev/ram5: 4 MiB, 4194304 bytes, 8192 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes


Disk /dev/ram6: 4 MiB, 4194304 bytes, 8192 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes


Disk /dev/ram7: 4 MiB, 4194304 bytes, 8192 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes


Disk /dev/ram8: 4 MiB, 4194304 bytes, 8192 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes


Disk /dev/ram9: 4 MiB, 4194304 bytes, 8192 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes


Disk /dev/ram10: 4 MiB, 4194304 bytes, 8192 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes


Disk /dev/ram11: 4 MiB, 4194304 bytes, 8192 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes


Disk /dev/ram12: 4 MiB, 4194304 bytes, 8192 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes


Disk /dev/ram13: 4 MiB, 4194304 bytes, 8192 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes


Disk /dev/ram14: 4 MiB, 4194304 bytes, 8192 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes


Disk /dev/ram15: 4 MiB, 4194304 bytes, 8192 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes


Disk /dev/mmcblk0: 14.47 GiB, 15523119104 bytes, 30318592 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: dos
Disk identifier: 0xdeedbeef

Device         Boot   Start      End  Sectors  Size Id Type
/dev/mmcblk0p1 *          1   524288   524288  256M  c W95 FAT32 (LBA)
/dev/mmcblk0p2       524289  2621440  2097152    1G 83 Linux
/dev/mmcblk0p3      2621441 30318591 27697151 13.2G 83 Linux


Disk /dev/sda: 3.51 GiB, 3753902080 bytes, 7331840 sectors
Disk model: Flash Disk      
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: dos
Disk identifier: 0x00000000

**/media/usb1/backup$ /bin/df -a -T**

Filesystem           Type       1K-blocks      Used Available Use% Mounted on
/dev/root            ext4          999320    509548    420960  55% /
devtmpfs             devtmpfs      491384         0    491384   0% /dev
proc                 proc               0         0         0   0% /proc
devpts               devpts             0         0         0   0% /dev/pts
tmpfs                tmpfs         495992         0    495992   0% /dev/shm
tmpfs                tmpfs         495992       148    495844   0% /tmp
tmpfs                tmpfs         495992       136    495856   0% /run
sysfs                sysfs              0         0         0   0% /sys
tmpfs                tmpfs         495996      3756    492240   1% /var
tmpfs                tmpfs         495992         0    495992   0% /media
/dev/mmcblk0p3       ext4        13565404    583416  12273176   5% /usr/local
/dev/mmcblk0p1       vfat          261868     47444    214424  18% /boot
/dev/sda             vfat         3658752    364184   3294568  10% /media/usb1

**Comment by j-a-n** [comment]
Kannst Du bitte nochmal die neue Version 1.13.15 einspielen?
Hier wird die Fehlermeldung hoffentlich nochmal etwas detaillierter.

**Comment by ThomasRi333** [comment]
Hallo Jan, leider funktioniert kein Update. Manuell nicht , und auch nicht über den Updater.
Fehlermeldung:
<html><head><meta http-equiv="refresh" content="0; url=https://github.com/j-a-n/raspberrymatic-addon-rmupdate/raw/master/rmupdate.tar.gz" /></head><body><a href="https://github.com/j-a-n/raspberrymatic-addon-rmupdate/raw/master/rmupdate.tar.gz">https://github.com/j-a-n/raspberrymatic-addon-rmupdate/raw/master/rmupdate.tar.gz</a></body></html>

... erscheint als Textmeldung...

**Comment by j-a-n** [comment]
Dann bitte über die Systemsteuerung der ccu einspielen.

**Comment by ThomasRi333** [comment]
Da bekomme ich den Hinweis, es ist kein korrektes Plugin...

**Comment by ThomasRi333** [comment]
Sorry Jan, die Installation funktioniert jetzt.
![A4B3A93F-130F-48B1-828A-415E940512CC](https://user-images.githubusercontent.com/59541201/72363775-ad43a380-36f5-11ea-961d-b5c02090ef15.jpeg)

Nochmal über SSH die Ergebnisse ?

**Comment by j-a-n** [comment]
Danke, als nächstes benötige ich den Output von:
```
parted /dev/mmcblk0 unit B print
parted /dev/sda unit B print
```

**Comment by ThomasRi333** [comment]
Hallo Jan,
hier die Ausgabe:

/$ parted /dev/mmcblk0 unit B print
Model: SD SD16G (sd/mmc)
Disk /dev/mmcblk0: 15523119104B
Sector size (logical/physical): 512B/512B
Partition Table: msdos
Disk Flags: 

Number  Start        End           Size          Type     File system  Flags
 1      512B         268435967B    268435456B    primary  fat16        boot, lba
 2      268435968B   1342177791B   1073741824B   primary  ext4
 3      1342177792B  15523119103B  14180941312B  primary  ext4

/$ parted /dev/sda unit B print
Model: Generic Flash Disk (scsi)
Disk /dev/sda: 3753902080B
Sector size (logical/physical): 512B/512B
Partition Table: loop
Disk Flags: 

Number  Start  End          Size         File system  Flags
 1      0B     3753902079B  3753902080B  fat32


... und DANKE für deine Unterstützung. Ist ja nicht selbstverständlich.

**Comment by j-a-n** [comment]
BItte noch folgende Ausgabe posten:
```
/sbin/blkid /dev/mmcblk0p1
/sbin/blkid /dev/mmcblk0p2
/sbin/blkid /dev/mmcblk0p3
/sbin/blkid /dev/sda1
```

**Comment by ThomasRi333** [comment]
/$ /sbin/blkid /dev/mmcblk0p1
/dev/mmcblk0p1: SEC_TYPE="msdos" LABEL_FATBOOT="bootfs" LABEL="bootfs" UUID="78CE-B316" TYPE="vfat" PARTUUID="deedbeef-01"
/$ /sbin/blkid /dev/mmcblk0p2
/dev/mmcblk0p2: LABEL="rootfs" UUID="e5e26241-a602-4dad-a005-38c6776e585a" TYPE="ext4" PARTUUID="deedbeef-02"
/$ /sbin/blkid /dev/mmcblk0p3
/dev/mmcblk0p3: LABEL="userfs" UUID="bd409913-0e48-4fe3-890f-0ec7fb569418" TYPE="ext4" PARTUUID="deedbeef-03"
/$ /sbin/blkid /dev/sda
/dev/sda: LABEL_FATBOOT="Raspi" LABEL="Raspi" UUID="619B-4DD1" TYPE="vfat"

**Comment by j-a-n** [comment]
Bitte die Version 1.13.16 versuchen.

**Comment by ThomasRi333** [comment]
Hallo Jan, ich glaube einer der Hauptfehler sitzt gerade an der Tastatur...
Ich werde erst einmal alles neu aufsetzen, alle Geräte ablernen und meine CCU2 (Lan-Gateway) dumm machen. (Mit einer älteren Raspberrymatic scheint das zu funktionieren, die Version ist 3.47)
Ich melde mich sobald dieses erledigt ist. 
Sorry....

**Comment by j-a-n** [comment]
Kein Problem.
