### ISSUE TITLE
"ova", "rpi4" und "intelnuc" werden nicht unter "System-Typ:" erkannt

### ISSUE THREAD

**Issue by jens-maus** [j-a-n/raspberrymatic-addon-rmupdate#23]
Beim Test deines Addons ist mir gerade aufgefallen das anscheinend für die neueren RaspberryMatic platformen (rpi4, ova, intelnuc) auf der Konfigurationsseite unter "System-Typ:" diese nicht aufgelistet werden:

<img width="506" alt="Bildschirmfoto 2020-01-26 um 11 29 58" src="https://user-images.githubusercontent.com/5887769/73133915-89eef180-402f-11ea-945c-aa38ebdeaae2.png">

Dies könnte natürlich mitunter zu gewissen problemen führen...

**Comment by j-a-n** [comment]
Behoben in Version 1.14.0
