### ISSUE TITLE
Wrong system version is installed.

### ISSUE THREAD

**Issue by FrodoVDR** [j-a-n/raspberrymatic-addon-rmupdate#25]
Today I was offered a new version from 3.49.17.20200201 which does not exist. While trying to install it, a version for Intel NUC was installed on my Tinkerboard S. Fortunately the installation failed and I was able to install the actual available version 3.49.17.20200131 via the Raspberrymatic GUI for Tinkerboard.

Even after installing version 3.49.17.20200131 I still get the message that there is a newer version 3.49.17.20200201 available.

**Comment by j-a-n** [comment]
Should be fixed with version 1.14.0
