### ISSUE TITLE
An error occurred: Command blkid failed for device /dev/sdb1: child process exited abnormally

### ISSUE THREAD

**Issue by mike-bee** [j-a-n/raspberrymatic-addon-rmupdate#26]
I am using rmupdate for quite some time with great satisfaction.

Recently I replaced my 64GB USB memory stick by a 2GB version. While it perfectly works for storing daily backups, rmupdate always throws above error message when building the Volume table at startup.

Here is the full message:
An error occurred: Command blkid failed for device /dev/sdb1: child process exited abnormally - NONE - Command blkid failed for device /dev/sdb1: child process exited abnormally
    while executing
"error "Command blkid failed for device ${part_dev}: ${err}""
    (procedure "rmupdate::get_partitions" line 72)
    invoked from within
"rmupdate::get_partitions"
    (procedure "process" line 61)
    invoked from within
"process"

With my limited linux knowledge I found that there is no sdb1 device but a "sdb" representing the new memory stick. 

Pleae have look into it. I am happy to assist if required.

**Comment by j-a-n** [comment]
Please try if version 1.14.4 resolves the issue.

**Comment by mike-bee** [comment]
Wow, this I call responsiveness.
I am happy to report that the issue seems to be fixed.
Many thanks.
