### ISSUE TITLE
Fehlermeldung und Firmwares werden nicht geladen auf RaspberryMatic vers. 3.51.6.20.200420

### ISSUE THREAD

**Issue by GitDriveHub** [j-a-n/raspberrymatic-addon-rmupdate#28]
Hallo,

ich habe RaspeberryMatic vers. vers. 3.51.6.20.200420 zu laufen mit rmupdate 1.14.4 und bekomme die nachfolgende Fehlermeldung, als auch die Firmwares können nicht geladen werden.

was kann ich machen? danke

Ein Fehler ist aufgetreten: child process exited abnormally - CHILDSTATUS 8144 4 - child process exited abnormally
    while executing
"exec /usr/bin/wget "${support_file_url}" --no-check-certificate -q -O-"
    (procedure "rmupdate::get_firmware_info" line 5)
    invoked from within
"rmupdate::get_firmware_info"
    (procedure "process" line 55)
    invoked from within
"process"

**Comment by j-a-n** [comment]
Der wget Fehlercode 4 deutet auf einen Netzwerfehler hin.
https://www.gnu.org/software/wget/manual/html_node/Exit-Status.html

Internetverbindung des Raspi prüfen.
