### ISSUE TITLE
Does not show available firmware version

### ISSUE THREAD

**Issue by TheUntouchable** [j-a-n/raspberrymatic-addon-rmupdate#29]
Hello and first of all thank you very much for this great addon to raspmatic!

Since some versions of the addon I have the problem that under Firmware only the currently installed fimware is displayed. Even though the front page of raspmatic says that there is a new version available, rmupdate doesn't tell me that.

Also the checkbox "Experimental Versions" does nothing.

The plugin has already been completely uninstalled, but this does not fix the problem.

The addon update function works without problems!

Is there anything I can do to fix it?

Many thanks in advance :)

![2020-06-23 10_00_29-Window](https://user-images.githubusercontent.com/2162540/85376917-a3da2500-b538-11ea-87b4-a76293f2a689.png)

**Comment by j-a-n** [comment]
Could you please have a look to the browser console (F12)?
Are there any errors in the console?

**Comment by chrostek** [comment]
i have the same problem - but only on System-Typ: ova-KVM and rpi2 (i use the plugin on several systems, rpi3 works.
the browser console shows only an error with wlan_scan on this system types, because they have no wlan

**Comment by TheUntouchable** [comment]
Also a RPI2 here and also only the WLAN error in the console as I don't have any wlan stick attached to the pi :)

**Comment by chrostek** [comment]
i think the problem is here:

https://github.com/j-a-n/raspberrymatic-addon-rmupdate/blob/d580059c76c2b79272d24463ae2f3f6f142366b2/addon/lib/rmupdate.tcl#L1067

the version rpi2 needs to be mapped to rpi3 (because there are only download links for rpi3) and ova-KVM needs to be mapped to ova

**Comment by j-a-n** [comment]
Please try version 1.14.5

**Comment by chrostek** [comment]
there is no 1.14.5 in this repo - did you upload it? ;-)

**Comment by j-a-n** [comment]
Sorry, push failed.

**Comment by chrostek** [comment]
does not work :-(

![image](https://user-images.githubusercontent.com/4532704/85408360-b5392680-b564-11ea-8c31-c77be3084a7a.png)

**Comment by j-a-n** [comment]
I see... please try again with 1.14.6

**Comment by chrostek** [comment]
works for me for rpi2 and ova-KVM - thanks!

**Comment by TheUntouchable** [comment]
Also working here, thank you! :D

**Comment by makuris** [comment]
Hello, 

Thank you for this great addon.

I also have the issue described above. The console says "Failed to load resource: /addons/rmupdate/rest.cgi?sid=@R3CTA9nioZ@&path=/wlan_scan:1  the server responded with a status of 500 (Internal Server Error)"

I am using version 1.14.12 and also running an OVA version on a NAS without WLAN.
How can I fix this?

Thank you in advance!

**Comment by j-a-n** [comment]
Please try version 1.14.13

**Comment by makuris** [comment]
Thank you for your fast repsones!

I now tried 1.14.13 - The error message seems to be gone.

However it still states that there is no update available:
Momentan installierte Version: 3.53.30.20200919
Aktuellste verfügbare Version: 3.53.30.20200919

On the redmatic start page it says:

Aktuelle Firmwareversion: | 3.53.30.20200919
RaspMatic-Update: | Firmware 3.53.34.20201121 ist verfügbar

**Comment by j-a-n** [comment]
What is stated as "System Type" at the top of the page?

**Comment by makuris** [comment]
System-Typ: ova-Microsoft

**Comment by j-a-n** [comment]
Okay, please try version 1.14.14

**Comment by makuris** [comment]
Yoo-Hoo, it worked :-)

Momentan installierte Version: 3.53.30.20200919
Aktuellste verfügbare Version: 3.53.34.20201121

Thank you so much!
