### ISSUE TITLE
Experimentelle Versionen

### ISSUE THREAD

**Issue by Bono1969** [j-a-n/raspberrymatic-addon-rmupdate#30]
Wenn ich die Auswahl treffe wird auch eine experimentelle Version angezeigt. Wenn ich diese auswähle kommt ein 404 Fehler von GitHub. Was mache ich falsch?

**Comment by j-a-n** [comment]
Kannst Du bitte einmal die Version 1.14.7 versuchen?

**Comment by Bono1969** [comment]
Installiert, gebootet, leider keine Verbesserung. Fehlermeldung identisch.

**Comment by Bono1969** [comment]
Uups geht doch.
Wenn man auf die Version klickt welche ja als Link ausgebildet ist, erscheint die 404 Meldung von GitHub.
Wenn man jedoch einfach auf den installieren Button drückt, wird die Version anstandslos installiert. Danke für den Turbo Service 👍

**Comment by j-a-n** [comment]
Ah, okay, das schaue ich mir dann noch an.

**Comment by Bono1969** [comment]
Du bist wirklich auf Zack, Hut ab.
Habe die neue Version installiert und nun klappt auch der Link.
Was ein wenig seltsam ist, dass wenn man so eine Beta installiert, es eine zusätzliche Versionsnummer anzeigt bei der der Link natürlich nicht geht weil es die ja gar nicht gibt. Anbei ein Screenshot
![706FE491-B1B4-481F-97B3-8E0BA6E418DD](https://user-images.githubusercontent.com/37637519/85929016-8ea32480-b8b1-11ea-9932-53860807af32.jpeg)

**Comment by Bono1969** [comment]
Noch etwas.
Obwohl der Schalter WLAN auf aus steht, werden die verfügbaren Wlans angezeigt. Wird das gecacht?
![E0A98690-6268-42BE-832C-5A1E788EC5C3](https://user-images.githubusercontent.com/37637519/85929065-01140480-b8b2-11ea-83d5-0fdfb6583109.jpeg)

**Comment by Bono1969** [comment]
Vorschlag:
Bei den Aktionen für den USB Stick die Funktion „nur Formatieren“ einfügen. Vielleicht sogar mit der von Jens vorgeschlagenen F2FS. Eine zusätzliche Sicherheitsabfrage vor Durchführung wäre sicher sinnvoll.
![0D72D753-85E3-4978-A989-D04D34ACCE15](https://user-images.githubusercontent.com/37637519/85929210-379e4f00-b8b3-11ea-85b8-58da2fcef1ca.jpeg)

**Comment by j-a-n** [comment]
Bitte für jedes Thema ein Issue aufmachen, dieses ist geschlossen.
