### ISSUE TITLE
Versionsnummer wenn experimentelle Version installiert 

### ISSUE THREAD

**Issue by Bono1969** [j-a-n/raspberrymatic-addon-rmupdate#31]
Wenn man eine Beta installiert hat, zeigt es eine zusätzliche Versionsnummer an, bei welcher der Link selbstverständlich nicht funktioniert weil es die gar nicht gibt.
![742A663D-FC2C-4EED-8CFF-48310FBE2684](https://user-images.githubusercontent.com/37637519/85951186-ce294980-b961-11ea-9f02-adc3842c8ae4.jpeg)

**Comment by j-a-n** [comment]
Sollte mit Version 1.14.9 behoben sein.

**Comment by Bono1969** [comment]
Installiert, getestet 👍🏻
