### ISSUE TITLE
WLAN Anzeige

### ISSUE THREAD

**Issue by Bono1969** [j-a-n/raspberrymatic-addon-rmupdate#32]
Obwohl der Schalter WLAN auf aus steht, werden die verfügbaren Wlans angezeigt.
Ist das so gedacht? Wird das gecacht?
Ist nur ein „Schönheitsfehler“...vielleicht 😉
![DA7D5795-985F-42FF-A007-6F7EBD330F9F](https://user-images.githubusercontent.com/37637519/85951255-4bed5500-b962-11ea-97ef-9949d9946778.jpeg)

**Comment by j-a-n** [comment]
Ja, die Liste der verfügbaren WLANs wird einmal beim Laden abgerufen.
Wenn der Schalter aktiviert ist, wird kontinuierlich gescannt.
