### ISSUE TITLE
rmupdate auch bei visualisierter Installation

### ISSUE THREAD

**Issue by MathiasJZ** [j-a-n/raspberrymatic-addon-rmupdate#35]
Ich möchte bald vom Raspberry auf den NUC umsteigen.
Ich habe auf "dumm" versucht, auch dort rmupdate zu installieren.
Die Installation selbst ist kein Problem. Es wäre toll, wenn man auch dort die Vorzüge von rmupdate nutzen könnte.
Alleine ein Update via Fernwartung anzustoßen ist einfach super.
Eine Deinstallation ist leider auf dem Proxmox nicht mehr möglich. 
Vielleicht habe ich etwas verpaßt, weil ich nicht mehr weiß, welche Version ich benutzt habe.

**Comment by j-a-n** [comment]
rmupdate funktioniert auch mit der OVA-Version von RaspberryMatic.
Ich selbst habe eine Instanz unter Proxmox laufen.

**Comment by MathiasJZ** [comment]
OK danke
Dann wird das wohl die letzte Version gewesen sein.
Ich war mir leider nicht sicher.
Gruß,
Mathias
