### ISSUE TITLE
Latest firmware update will kill rp2 installation

### ISSUE THREAD

**Issue by TheUntouchable** [j-a-n/raspberrymatic-addon-rmupdate#36]
As there are very big changes in the new raspmatic version, you will simply kill your current installation when updating via rmupdate, as there is now a separate image for rp2!

**Comment by TheUntouchable** [comment]
https://github.com/jens-maus/RaspberryMatic/releases/tag/3.53.34.20201121
Existing users with a RaspberryPi2 hardware have to reinstall their SD card from scratch due to the fact that from now on there are dedicated release archives for the rpi2 target (don't use the rpi3 anymore!). Thus, please create a fresh backup, reflash your SD card with the rpi2 image file and reinstall the backup accordingly. Afterwards you should have a working system again and have to use the rpi2 download archives in future.

**Comment by j-a-n** [comment]
Thanks for the hint. In version 1.14.11 hardware versions a01040, a01041, a21041, a22042 are now mapped to the rpi2 image.

**Comment by chrostek** [comment]
This does not work ...
https://github.com/j-a-n/raspberrymatic-addon-rmupdate/blob/3f92132b7ab9353bf5168d5867551be75af16abd/addon/lib/rmupdate.tcl#L1067
you rewrite rpi2 to rpi3 later in this file ;-)

**Comment by j-a-n** [comment]
Thanks, fixed in 1.14.12
