### ISSUE TITLE
Update fails with 2.29.23.20171022

### ISSUE THREAD

**Issue by chrostek** [j-a-n/raspberrymatic-addon-rmupdate#4]
The update to version 2.29.23.20171022 fails with the following error message:

`An error occurred: Length Date Time Name --------- ---------- ----- ---- 560914944 10-22-2017 01:07 RaspberryMatic-2.29.23.20171022-rpi3.img 117 10-22-2017 01:07 RaspberryMatic-2.29.23.20171022-rpi3.img.sha256 11357 12-09-2016 14:08 LICENSE -------- ------- 560926418 3 files unzip: removing leading '../' from member names`

**Comment by j-a-n** [comment]
Thanks for reporting.
The exec treats any output to standard error to be an indication that the external program failed.
Therefore stderr is now redirected to /dev/null.
Fixed with version 1.1.3
