### ISSUE TITLE
rmupdate funktioniert nicht

### ISSUE THREAD

**Issue by comtechnik** [j-a-n/raspberrymatic-addon-rmupdate#5]
Hallo,
ich versuche des öfteren schon mit dem neuen Image und dem rmupdate das System-Update zu installieren.
Leider funktioniert es nicht da ich keine neuer Firmware als die 2.31.25.20180220 angezeigt bekomme.
Auf der Startseite wird mir aber angezeigt das eine neuere verfügbar ist die 2.31.25.20180225.
Kann es sein das es auf dem Raspberry 2 mit dem Image RaspberryMatic-2.31.25.20180120-rpi3.rmupdate
nicht funktioniert ?? Hab es auch mit dem  Image RaspberryMatic-2.31.25.20180120-rpi0.rmupdate versucht, da startet der Raspberry nicht.
Bitte um ihre Hilfe
Danke
![raspmatic](https://user-images.githubusercontent.com/10614494/37253227-1835f574-252f-11e8-8ab1-4ba3758e15eb.JPG)
![raspmatic2](https://user-images.githubusercontent.com/10614494/37253228-18514a22-252f-11e8-8004-bbcac61e1107.JPG)

**Comment by j-a-n** [comment]
Hallo,

was wird unter den System-Informationen bei System-Typ angezeigt?
Kommst Du per SSH auf das System?
Wenn ja , was liefert der folgende Befehl:
`cat /proc/cpuinfo`

**Comment by comtechnik** [comment]
login as: root
root@192.168.2.243's password:
# cat /proc/cpuinfo
processor       : 0
model name      : ARMv7 Processor rev 5 (v7l)
BogoMIPS        : 38.40
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xc07
CPU revision    : 5

processor       : 1
model name      : ARMv7 Processor rev 5 (v7l)
BogoMIPS        : 38.40
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xc07
CPU revision    : 5

processor       : 2
model name      : ARMv7 Processor rev 5 (v7l)
BogoMIPS        : 38.40
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xc07
CPU revision    : 5

processor       : 3
model name      : ARMv7 Processor rev 5 (v7l)
BogoMIPS        : 38.40
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xc07
CPU revision    : 5

Hardware        : BCM2835
Revision        : 1a01041
Serial          : 00000000e80d29cd
#

**Comment by comtechnik** [comment]
Wo finde ich System-Informationen / System-Typ

**Comment by j-a-n** [comment]
Fixed in 1.9.12

**Comment by comtechnik** [comment]
Super, vielen Dank !!
Mit 1.9.12 funktioniert es jetzt !!!
