### ISSUE TITLE
Raspberry startet neu, wenn ich das Addon rmupdate ausführe

### ISSUE THREAD

**Issue by markoox** [j-a-n/raspberrymatic-addon-rmupdate#6]
Hallo zusammen,

wenn ich bei meinem Raspberry unter Einstellungen/Systemsteuerung/System-Update gehen, wird versucht die Tabelle aufzubauen:

![image](https://user-images.githubusercontent.com/27847082/37268820-1f253d6a-25c8-11e8-8107-63ca2556c73e.png)

Dabei startet der Raspberry aber neu, und die Tabelle wird nicht aufgebaut.

Folgende Versionen sind installiert: Homematic: 2.31.25.20180225
RMupdate: 1.9.12

Danke für eine Info

Gruß

Marko Ochs

**Comment by j-a-n** [comment]
Welche Addons sind installiert?

**Comment by markoox** [comment]
Hallo,

diese Addons sind installiert:

![bildschirmfoto 2018-03-12 um 08 18 58](https://user-images.githubusercontent.com/27847082/37270174-14d0b94c-25ce-11e8-8e5e-721f6eea82a5.png)


Gruß

Marko Ochs

**Comment by markoox** [comment]
Hallo, welche Informationen wären denn noch Hilfreich?

Ich habe das Addon auch noch mal deinstalliert und wieder neu installiert. Dabei ist der Raspberry nicht wieder alleine hoch gekommen. Musste ihn kurz vom Strom nehmen, und dann neu starten, dann war er wieder über die Weboberfläche erreichbar.

Aber das Problem mit dem Tabellenaufbau und dem Neustarten bei dieser Aktion ist geblieben.

Gruß

Marko

**Comment by j-a-n** [comment]
Hallo,

kannst Du bitte einmal versuchen, ob das Problem mit der Version 1.9.13 behoben ist?

Grüße
Jan

**Comment by markoox** [comment]
Guten Morgen,

leider ist das Problem immer noch so. Es wird versucht die Tabelle aufzubauen, die Greise Drehen sich und der Raspberry startet mehr Mals neu. Dies merke ich daran, das ich immer nach einem Neustart eine eMail bekomme, das der Duty Cycle über 50% ist.

Gruß

Marko Ochs

**Comment by markoox** [comment]
Hallo, mal kurz zur Info, was ich jetzt alles noch mal probiert habe:

1. alle Addons deinstalliert, bis auf Cux Daemon
2. dann das rmupdate 1.9.13 installiert

Test, gleiches Problem weiterhin.

Habe  jetzt wieder den Ursprung hergestellt. Alle Addons wieder installiert.

Gruß

Marko Ochs

**Comment by j-a-n** [comment]
Seltsames Verhalten. Ich habe aktuell keine Idee wodurch der Reboot ausgelöst werden könnte.
Ist vielleicht die Hardware defekt? Netzteil zu schwach? SD-Karte defekt?

**Comment by markoox** [comment]
Hallo, SD Karte kann ich ausschließen, denn ich habe gestern eine 2. SD Karte vorbereitet und eingerichtet. Ich bin wie folgt vorgegangen:

SD Karte mit dem Image: https://github.com/j-a-n/raspberrymatic-addon-rmupdate 
installiert, dann Raspberry gestartet, Addon Cux Daemon installiert, dann RM-Update Addon installiert, noch kein Backup installiert und versucht über Systemupdate auf diese Seite zukommen:

![bildschirmfoto](https://user-images.githubusercontent.com/27847082/37557145-905a0f7e-2a00-11e8-8ecb-3a6b491197f2.png)

doch gleiches verhalten. Ich habe mir jetzt mal einen neuen Raspberry bestellt, wenn der da ist, dann werde ich alles noch mal Probieren.

Gruß

Marko Ochs

**Comment by markoox** [comment]
Hallo, ich habe das Problem gefunden, es war der Raspberry. Habe heute einen neuen Raspberry erhalten, die Speicherkarte des alten in den Neuen, und alles geht.

So kam der Neustart des Gerätes bei Aufruf des rmupdate Addon durch Hardware defekt.

Aber schon mal Danke für die Unterstützung.

Gruß

Marko Ochs
