### ISSUE TITLE
 rmupdate 1.11.0 doesn't work with raspberrymatic 2.31.25.20180428

### ISSUE THREAD

**Issue by FrodoVDR** [j-a-n/raspberrymatic-addon-rmupdate#7]
After update to the new version with rmupdate 1.11.0, I do update raspberrymatic to version 2.31.25.20180428. Now I see a error message "Ein Fehler ist aufgetreten: can&#39;t read &quot;current_version&quot;: no such variable" and many unknown /dev/ram0-15 .

**Comment by j-a-n** [comment]
Which RaspberryMatic version is currently installed?

**Comment by Auvikal** [comment]
I have the same problem with rmupdate 1.11.1. 
RaspberryMatic version 2.31.25.20180428

**Comment by FrodoVDR** [comment]
I use RaspberryMatic 2.31.25.20180428 (I wrote this in the issue name) and with rmupdate 1.11.1 it is the same issue.

On the Firmware section I see only a circle ring. My hardware is rpi3.

**Comment by j-a-n** [comment]
Fixed in 1.11.2.
