### ISSUE TITLE
Frage zur Installation eines Addons ohne Neustart

### ISSUE THREAD

**Issue by jp112sdl** [j-a-n/raspberrymatic-addon-rmupdate#9]
Moin!

Ich habe übers HM-Forum mitbekommen, dass es möglich ist, mit dem `rmupdate`-Plugin Addons zu installieren, ohne einen Neustart durchzuführen.

Vermutlich entpackst du die `.tgz` und führst das darin enthaltene `update-script` aus, wie es auch bei der Addoninstallation auf der CCU2 erfolgt.

Nun setzt mein Addon eigentlich auf den gewohnten Reboot, weil dabei der ReGaHss Dienst neu gestartet wird. 
Desweiteren wird ein rc-Script installiert. Wird das nach der Addoninstallation via `rmupdate` sofort ausgeführt?
Und wird dem `update-script` noch ein Parameter übergeben, so dass ich erkennen könnte, dass die Installation des Addons via `rmupdate` ausgeführt wird?

LG,
JP

**Comment by j-a-n** [comment]
Hallo Jérôme,

ja, nach der Installation wird das rc-Skript mit dem Parameter restart ausgeführt.
Dem update_script wird aktuell nur der Parameter "HM-RASPBERRYMATIC" übergeben.

Grüße,
Jan
